wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    # clocks_a:
    #   colors:
    #     rows:
    #       even: "lightblue"
    #       odd: "white"
    #   enabled: true
    #   locations:
    #     NewYork: "America/New York"
    #   position:
    #     top: 0
    #     left: 0
    #     height: 1
    #     width: 1
    #   refreshInterval: 15
    #   sort: "alphabetical"
    #   title: "Clocks A"
    #   type: "clocks"
    cmdrunner:
      args: ["-h", "-P"]
      cmd: "df"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 3
    subreddit:
      enabled: false
      numberOfPosts: 5
      position:
        top: 4
        left: 1
        height: 3
        width: 2
      refreshInterval: 900
      sortOrder: top
      subreddit: "netsec"
      topTimePeriod: hour
    todo:
      checkedIcon: "X"
      colors:
          checked: gray
          highlight:
            fore: "black"
            back: "orange"
      enabled: true
      filename: "todo.yaml"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    digitalclock:
      color: orange
      enabled: true
      font: bigfont
      hourFormat: 12
      position:
        top: 0
        left: 4
        height: 1
        width: 1
      refreshInterval: 1
      title: "big clock"
      type: "digitalclock"
    security:
      enabled: true
      position:
        top: 1
        left: 5
        height: 1
        width: 1
      refreshInterval: 3600
    prettyweather:
      enabled: true
      city: "West Chester"
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 2
        left: 0
        height: 1
        width: 3
      storyType: top
      refreshInterval: 900
    textfile:
      enabled: false
      filePath: "~/.config/wtf/config.yml"
      format: true
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 30
      wrapText: false
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 5
        height: 1
        width: 1
      refreshInterval: 8
      repositories:
      - "~/Research/Consulting/ObjectSecurity"
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
