# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
export DYLD_LIBRARY_PATH=/usr/local/opt/unicorn/lib/:$DYLD_LIBRARY_PATH
export HOMEBREW_GITHUB_API_TOKEN="9331bad17edcfd106f786d12164164b7b6119b99"
#export ZSH_THEME="omega-minimal"
export ZSH_THEME="powerlevel9k/powerlevel9k"
export POWERLEVEL9K_DISABLE_RPROMPT=false
# export ZSH_THEME="avit"

# CASE_SENSITIVE="true"

export EDITOR="vim"
# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git vim osx man httpie brew autojump pip python themes virtualenv)

source $ZSH/oh-my-zsh.sh
export TERM=screen-256color

# Customize to your needs...

export PATH="$PATH:/usr/local/opt/qt/bin"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export PATH="$PATH:/usr/local/sbin:/usr/local/share:/Users/jdefr89/bin/javacc-5.0/bin"
export PATH="$PATH:/Users/jdefr89/.rvm/gems/ruby-1.9.2-p318/bin:/Users/jdefr89/.rvm/gems/ruby-1.9.2-p318@global/bin:/Users/jdefr89/.rvm/rubies/ruby-1.9.2-p318/bin:/Users/jdefr89/.rvm/bin:/sw/bin:/sw/sbin:/opt:/usr/local/bin:/usr/sbin:/usr/bin:/usr/share:/bin:/usr/games:/sbin:/Users/jdefr89/.rvm/bin:/Users/jdefr89/.bin:/usr/X11R6/bin:/Users/jdefr89/.rvm/bin"
export PATH="$PATH:/usr/local/opt/ruby@2.2/bin"


export GOPATH=$HOME/programming/Go

export CDPATH=.:~:/etc:/var:~/programming

# Django (Python web-framework, needed these set!)
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Develop armjitsu
alias ls="exa"

# My Custom Aliases
alias lsusb='system_profiler SPUSBDataType'
alias shuf="gshuf"
alias gdb="sudo gdb"
alias cat="ccat"
alias mvim='mvim --remote-silent'
alias vim='vim'

# Alias to manage and update config for zsh and vim
alias so='source .zshrc && hash -r'
alias zed='vim ~/.zshrc'

# Grab external IP

alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias dnsinuse="dig whoami.akamai.net +short"

# Custom exports

export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";
export HISTFILE=~/.zhistory

# Autojump - quick navigation for zsh, a godsend.
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# For markers, to remember past commands and easy access.
[[ -s "$HOME/.local/share/marker/marker.sh" ]] && source "$HOME/.local/share/marker/marker.sh"

# Base16 Shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


alias t='todolist'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

